platform :ios, '14.0'
use_frameworks!

target 'SpendCraftiOS' do
  # Shared KMP Framework
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
      # SQLite linking için - iOS'ta built-in SQLite3 kullan
      if target.name == 'shared'
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -lsqlite3'
        config.build_settings['LIBRARY_SEARCH_PATHS'] = '$(inherited) $(SDKROOT)/usr/lib'
      end
    end
  end
  
  # Ana proje için de SQLite linking ekle
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -lsqlite3'
      end
    end
  end
end
